import React from 'react';
import { MatchHistory, Player, UserProfile } from '../types';
import { lineService } from '../services/lineService';

interface MatchHistoryListProps {
    history: MatchHistory[];
    allPlayers: Player[];
    onClose: () => void;
    currentUser: UserProfile | null;
}

const MatchHistoryList: React.FC<MatchHistoryListProps> = ({ history, allPlayers, onClose, currentUser }) => {
    const [isCopied, setIsCopied] = React.useState(false);

    const handleShare = async () => {
        console.log('handleShare called');
        if (history.length === 0) return;

        // 生成報表
        const dateStr = new Date().toLocaleDateString('zh-TW');
        let report = `🏸 羽球對戰紀錄 (${dateStr})\n`;
        report += `總場次: ${history.length} 場\n\n`;

        [...history].reverse().forEach((match, idx) => {
            const time = new Date(match.timestamp).toLocaleTimeString('zh-TW', { hour: '2-digit', minute: '2-digit' });
            report += `R${history.length - idx} (${time})` + (match.duration ? ` ⏱${Math.floor(match.duration / 60)}m` : '') + '\n';

            // Team A
            const teamA = match.teams[0].map(id => allPlayers.find(p => p.id === id)?.name || '?').join('&');
            // Team B
            const teamB = match.teams[1].map(id => allPlayers.find(p => p.id === id)?.name || '?').join('&');

            report += `${teamA} vs ${teamB}`;

            if (match.score) {
                report += `\n🏅 ${match.score[0]} : ${match.score[1]}`;
            }
            report += '\n------------------\n';
        });

        report += '\nGenerated by ShuttleMaster AI';

        let errorAlerted = false;
        if (currentUser) {
            console.log('User logged in, attempting Line share...');
            try {
                const result = await lineService.shareMessage(report);
                console.log('Line share result:', result);

                if (result.success) {
                    alert('已發送至 Line！');
                    return;
                }

                // 顯示具體錯誤，除非是使用者自己取消
                if (result.error && result.error !== '使用者取消分享' && result.error !== '已取消分享') {
                    alert(`Line 分享失敗：${result.error}\n已自動複製文字到剪貼簿！`);
                    errorAlerted = true;
                }
            } catch (e) {
                console.error('Line share exception:', e);
            }
        }

        // Fallback or Manual
        console.log('Writing to clipboard...');
        navigator.clipboard.writeText(report).then(() => {
            console.log('Clipboard write success');
            setIsCopied(true);
            setTimeout(() => setIsCopied(false), 2000);
        }).catch(err => {
            console.error('Clipboard failed', err);
            alert('複製失敗，請手動複製 console 內容');
        });
    };

    const getPlayerName = (id: string, idx: number) => {
        const player = allPlayers.find(p => p.id === id);
        if (!player) return <span className="text-slate-400">?</span>;
        return (
            <span className="font-bold">
                {player.name}
                <span className="text-[10px] text-slate-400 font-normal ml-1">L.{player.level}</span>
            </span>
        );
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-white rounded-3xl shadow-2xl w-full max-w-2xl max-h-[80vh] flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
                <div className="p-6 border-b flex items-center justify-between bg-slate-50">
                    <h2 className="text-xl font-black text-slate-800 flex items-center gap-2">
                        <span className="text-2xl">📜</span> 對戰歷史紀錄
                    </h2>
                    <div className="flex items-center gap-2">
                        <button
                            onClick={handleShare}
                            disabled={isCopied}
                            className={`px-3 py-1.5 rounded-xl flex items-center gap-1.5 text-xs font-bold transition-all shadow-sm ${isCopied ? 'bg-emerald-100 text-emerald-700' : currentUser ? 'bg-[#00C300] text-white hover:bg-[#00b300]' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
                        >
                            {isCopied ? (
                                <>
                                    <span>✅</span>
                                    <span>已複製！</span>
                                </>
                            ) : currentUser ? (
                                <>
                                    <svg viewBox="0 0 24 24" className="w-4 h-4 fill-current"><path d="M21.16 7.64c-1.38-2.58-4.52-4.5-8.58-4.5C5.64 3.14 0 7.4 0 12.64c0 4.68 4.4 8.64 10.32 9.32.4.08.94.24.94.24l-2.22 3.32c-.36.46-.22.84 0 1.04.1.08.3.2.78 0 4.28-2.6 8.92-5.46 11.34-8.92 1.38-2.58 1.38-5.38 0-7.64z" /></svg>
                                    <span>存到 Line</span>
                                </>
                            ) : (
                                <>
                                    <span>📋</span>
                                    <span>複製文字</span>
                                </>
                            )}
                        </button>
                        <button
                            onClick={onClose}
                            className="w-8 h-8 rounded-full bg-slate-200 text-slate-500 hover:bg-slate-300 flex items-center justify-center transition-colors font-bold"
                        >
                            ✕
                        </button>
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto p-6 space-y-4 custom-scrollbar">
                    {history.length === 0 ? (
                        <div className="text-center py-20 text-slate-400 italic">尚未有對戰紀錄</div>
                    ) : (
                        [...history].reverse().map((match, idx) => {
                            const date = new Date(match.timestamp);
                            const timeStr = date.toLocaleTimeString('zh-TW', { hour: '2-digit', minute: '2-digit' });

                            // 計算隊伍強度
                            const getLevel = (ids: string[]) => ids.reduce((sum, id) => sum + (allPlayers.find(p => p.id === id)?.level || 0), 0);
                            const lv1 = getLevel(match.teams[0]);
                            const lv2 = getLevel(match.teams[1]);
                            const diff = Math.abs(lv1 - lv2);

                            return (
                                <div key={match.timestamp} className="bg-white border border-slate-100 rounded-2xl p-4 shadow-sm hover:shadow-md transition-shadow">
                                    <div className="flex items-center justify-between mb-3">
                                        <span className="text-xs font-bold text-slate-400 bg-slate-100 px-2 py-1 rounded-lg flex items-center gap-2">
                                            <span>#{history.length - idx} • {timeStr}</span>
                                            {match.duration && (
                                                <span className="text-indigo-500 bg-indigo-50 px-1.5 py-0.5 rounded border border-indigo-100 flex items-center gap-1">
                                                    <span>⏱</span>
                                                    <span>{Math.floor(match.duration / 60)}m {match.duration % 60}s</span>
                                                </span>
                                            )}
                                        </span>
                                        <div className="flex gap-2">
                                            <span className={`text-xs font-bold px-2 py-1 rounded-lg ${diff <= 2 ? 'bg-emerald-50 text-emerald-600' : diff >= 5 ? 'bg-red-50 text-red-600' : 'bg-amber-50 text-amber-600'}`}>
                                                強度差: {diff}
                                            </span>
                                            {match.score && (
                                                <span className="text-xs font-black px-2 py-1 rounded-lg bg-slate-800 text-white shadow-sm flex items-center gap-1">
                                                    <span>🏆</span>
                                                    <span>{match.score[0]} : {match.score[1]}</span>
                                                </span>
                                            )}
                                        </div>
                                    </div>

                                    <div className="flex items-center justify-between gap-4">
                                        {/* Team 1 */}
                                        <div className={`flex-1 rounded-xl p-3 flex flex-col gap-2 border transition-all ${match.score && match.score[0] > match.score[1] ? 'bg-yellow-50 border-yellow-300 ring-2 ring-yellow-200 shadow-md scale-[1.02]' : 'bg-indigo-50/50 border-indigo-100 opacity-80'}`}>
                                            {match.score && match.score[0] > match.score[1] && <div className="text-[10px] font-black text-yellow-600 uppercase text-center mb-1">WINNER 👑</div>}
                                            {match.teams[0].map((pid, i) => (
                                                <div key={i} className="flex items-center gap-2">
                                                    <div className="w-2 h-2 rounded-full bg-indigo-400"></div>
                                                    {getPlayerName(pid, i)}
                                                </div>
                                            ))}
                                        </div>

                                        <div className="font-black text-slate-300 italic text-xl">VS</div>

                                        {/* Team 2 */}
                                        <div className={`flex-1 rounded-xl p-3 flex flex-col gap-2 border transition-all ${match.score && match.score[1] > match.score[0] ? 'bg-yellow-50 border-yellow-300 ring-2 ring-yellow-200 shadow-md scale-[1.02]' : 'bg-amber-50/50 border-amber-100 opacity-80'}`}>
                                            {match.score && match.score[1] > match.score[0] && <div className="text-[10px] font-black text-yellow-600 uppercase text-center mb-1">WINNER 👑</div>}
                                            {match.teams[1].map((pid, i) => (
                                                <div key={i} className="flex items-center gap-2">
                                                    <div className="w-2 h-2 rounded-full bg-amber-400"></div>
                                                    {getPlayerName(pid, i)}
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                </div>
                            );
                        })
                    )}
                </div>
            </div>
        </div>
    );
};

export default MatchHistoryList;
